data_path:
  value: "./data/atis/"
vocab_path:
  value: "./data/atis/vocab.txt"
model_save_dir:
  value: "./ckpt/"
model_path:
  value: "atis_model.bin"
hidden_dim:
  value: 128
emb_dim:
  value: 300
emb_dropout:
  value: 0.8
lstm_dropout:
  value: 0.5
attention_dropout:
  value: 0.1
num_attention_heads:
  value: 8
max_len:
  value: 32
lr_scheduler_gamma:
  value: 0.5
batch_size:
  value: 32
epoch:
  value: 100
seed:
  value: 9
lr:
  value: 0.001
eps:
  value: 1e-12
user_mean:
  value: [0.2, 0.2, 0.2]
user_std:
  value: [0.2, 0.2, 0.2]
loss: # Choose from: ce, nce, sce, rce, nrce, gce, ngce, mae, nmae, nlnl, fl, nfl, dmi
  value: ["ce"]
alpha:
  value: 1.0
beta:
  value: 1.0
scale:
  value: 1.0
q:
  value: 0.7
