method: bayes
name: sweep-robust-slu
metric:
  name: "test intent_acc"
  goal: minimize
parameters:
  data_path:
    value: "./data/atis/"
  vocab_path:
    value: "./data/atis/vocab.txt"
  model_save_dir:
    value: "./ckpt/"
  model_path:
    value: "atis_model.bin"
  hidden_dim:
    value: 128
  emb_dim:
    value: 300
  emb_dropout:
    value: 0.8
  lstm_dropout:
    value: 0.5
  attention_dropout:
    value: 0.1
  num_attention_heads:
    value: 8
  max_len:
    value: 32
  lr_scheduler_gamma:
    value: 0.5
  batch_size:
    value: 32
  epoch:
    value: 100
  seed:
    value: 9
  lr:
    value: 0.001
  eps:
    value: 1e-12
  user_mean:
    values: [ [ 0 ], [ 0.2, 0.2, 0.2 ], [ 0.6, 0.6, 0.6 ], [ 0.2, 0.2, 0.2 ], [ 0.2, 0.2, 0.2 ] ]
  user_std:
    values: [ [ 0 ], [ 0.2, 0.2, 0.2 ], [ 0.2, 0.2, 0.2 ], [ 0.6, 0.6, 0.6 ], [ 0.6, 0.6, 0.6 ] ]
  loss:
    values: [ [ "ce" ], [ "nce" ], [ "sce" ], [ "rce" ], [ "nrce" ], [ "gce" ], [ "ngce" ], [ "mae" ], [ "nmae" ], [ "nce", "rce" ], [ "nce", "mae" ], [ "gce", "nce" ], [ "gce", "rce" ], [ "gce", "mae" ], [ "ngce", "nce" ], [ "ngce", "rce" ], [ "ngce", "mae" ], [ "mae", "rce" ] ]
  alpha:
    values: [ 0.7, 1.0 ]
  beta:
    values: [ 0.7, 1.0 ]
  scale:
    values: [ 0.7, 1.0 ]
  q:
    values: [ 0.5, 0.7, 0.9 ]
